# Generated by Django 5.2.1 on 2025-06-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='chave_acesso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
