# Generated by Django 5.2.1 on 2025-06-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comercio_chave_acesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='chave_acesso',
        ),
        migrations.AlterField(
            model_name='comercio',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='senha',
            field=models.CharField(max_length=100),
        ),
    ]
