# Generated by Django 5.2.1 on 2025-06-04 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_comercio_chave_acesso_alter_comercio_cnpj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('estoque', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catalogo', models.CharField(max_length=100)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.comercio')),
            ],
        ),
    ]
