# Generated by Django 5.2.1 on 2025-06-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comercio',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comercio',
            name='formas_pagamento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comercio',
            name='horario_funcionamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comercio',
            name='tipo_comercio',
            field=models.CharField(choices=[('Mecanico', 'Restaurante'), ('Chaveiro', 'Mercado'), ('açougue', 'Papelaria'), ('Brechó', 'Farmácia'), ('Marcenaria', 'Livraria'), ('Bijuteria', 'Barbeira'), ('Pedicure', 'Manicure'), ('Cabeleleiro', 'Dentista')], default='outros', max_length=50),
        ),
    ]
