# Generated by Django 5.2.1 on 2025-06-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comercio_descricao_comercio_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='tipo_comercio',
            field=models.CharField(choices=[('Mecanico', 'Mecânico'), ('Chaveiro', 'Chaveiro'), ('Acougue', 'Açougue'), ('Brecho', 'Brechó'), ('Marcenaria', 'Marcenaria'), ('Bijuteria', 'Bijuteria'), ('Pedicure', 'Pedicure'), ('Manicure', 'Manicure'), ('Cabeleireiro', 'Cabeleireiro'), ('Dentista', 'Dentista'), ('Restaurante', 'Restaurante'), ('Mercado', 'Mercado'), ('Papelaria', 'Papelaria'), ('Farmacia', 'Farmácia'), ('Livraria', 'Livraria'), ('Barbeiro', 'Barbeiro'), ('Outros', 'Outros')], default='Outros', max_length=50),
        ),
    ]
