# Generated by Django 5.2.1 on 2025-06-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_comercio_tipo_comercio'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendidos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
