# Generated by Django 5.2.1 on 2025-06-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_produto_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_estabelecimento',
            field=models.ImageField(blank=True, null=True, upload_to='comercios/'),
        ),
    ]
