# Generated by Django 5.2.1 on 2025-06-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_produto_imagem_estabelecimento_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='numero_local',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
