# Generated by Django 5.2.1 on 2025-06-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cliente_favoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='favoritos',
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
