# Generated by Django 5.2.1 on 2025-06-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_cliente_favoritos_cliente_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='clientes_favoritaram', to='core.comercio'),
        ),
    ]
