# Generated by Django 5.2 on 2025-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='')),
                ('comentarios', models.CharField(max_length=200)),
                ('historico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cormercio_produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('nome_produto', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('estoque', models.CharField(verbose_name=500)),
                ('preco', models.CharField(verbose_name=10)),
                ('descricao', models.CharField(verbose_name=200)),
                ('catalogo', models.CharField(verbose_name=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='comercio',
            name='senha',
        ),
    ]
