# Generated by Django 5.2.1 on 2025-06-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comercio_imagem_produto_imagem_estabelecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_estabelecimento',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
