# Generated by Django 5.2.1 on 2025-06-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_produto_numero_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='clientes_favoritaram', to='core.comercio'),
        ),
    ]
